// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEeuu62YMtEn8JlCgiNgB8pDB53Ccihfw',
    appId: '1:1077945520321:web:21244c4bd566f62f4ac440',
    messagingSenderId: '1077945520321',
    projectId: 'projeto-teorba',
    authDomain: 'projeto-teorba.firebaseapp.com',
    storageBucket: 'projeto-teorba.appspot.com',
    measurementId: 'G-4R2L0QL65Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCbIV7y9l_7d5UHnCcL-G98bWa30ATwrY',
    appId: '1:1077945520321:android:ef48021d55fb32434ac440',
    messagingSenderId: '1077945520321',
    projectId: 'projeto-teorba',
    storageBucket: 'projeto-teorba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkl6dsmAB_69ZBtIVywyrUtYeAQMFxmx0',
    appId: '1:1077945520321:ios:290ddfa5e6ff5f1d4ac440',
    messagingSenderId: '1077945520321',
    projectId: 'projeto-teorba',
    storageBucket: 'projeto-teorba.appspot.com',
    iosBundleId: 'com.example.flutterProjetinho',
  );
}
